### ISSUE TITLE
Put files into archive (ZIP, 7Z, RAR, ...)

### ISSUE THREAD

**Issue by anderlli0053** [SmilexGamer/NARTools#2]
@SmilexGamer 

Put the files into archive, right now you have to download each and every one separately as opposed to download whole archive and select the needed files from there.

![123](https://github.com/user-attachments/assets/27ab4d12-9476-404c-b753-e067ad3cd7ab)

**Comment by SmilexGamer** [comment]
You're right, that was dumb of me. Will update the files ASAP.

**Comment by anderlli0053** [comment]
> You're right, that was dumb of me. Will update the files ASAP.

Thanks and keep up the good work! 👍🏻
